create table if not exists public.commission_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null default '',
  email text not null default '',
  contact text not null default '',
  request_type text not null default '',
  people text not null default '',
  usage text not null default '',
  message text not null default '',
  status text not null default 'received'
);

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null default '',
  contact text not null default '',
  message text not null default '',
  status text not null default 'new'
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  page_path text not null default '',
  sender text not null default 'visitor',
  message text not null default ''
);

alter table public.commission_requests enable row level security;
alter table public.inquiries enable row level security;
alter table public.chat_messages enable row level security;

drop policy if exists "public can create commission requests" on public.commission_requests;
create policy "public can create commission requests"
  on public.commission_requests
  for insert
  to anon
  with check (true);

drop policy if exists "public can create inquiries" on public.inquiries;
create policy "public can create inquiries"
  on public.inquiries
  for insert
  to anon
  with check (true);

drop policy if exists "public can create chat messages" on public.chat_messages;
create policy "public can create chat messages"
  on public.chat_messages
  for insert
  to anon
  with check (true);

-- Admin read access should be added later with Supabase Auth.
-- Do not expose service_role keys in GitHub or browser code.
