create table if not exists public.commission_requests (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null default '',
  email text not null default '',
  contact text not null default '',
  request_type text not null default '',
  people text not null default '',
  usage text not null default '',
  message text not null default '',
  status text not null default 'received'
);

alter table public.commission_requests
add column if not exists reference_paths text[] not null default '{}';

create table if not exists public.inquiries (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  name text not null default '',
  contact text not null default '',
  message text not null default '',
  status text not null default 'new'
);

create table if not exists public.chat_messages (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  page_path text not null default '',
  sender text not null default 'visitor',
  message text not null default ''
);

create table if not exists public.admin_users (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

-- Auth 사용자가 한 명뿐이면 기존 관리자 계정으로 자동 등록합니다.
insert into public.admin_users (user_id)
select id from auth.users
where (select count(*) from auth.users) = 1
on conflict (user_id) do nothing;

alter table public.admin_users enable row level security;
drop policy if exists "users can check own admin access" on public.admin_users;
create policy "users can check own admin access"
  on public.admin_users
  for select
  to authenticated
  using (user_id = auth.uid());

create or replace function public.is_admin()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1 from public.admin_users where user_id = auth.uid()
  )
$$;
revoke all on function public.is_admin() from public;
grant execute on function public.is_admin() to authenticated;

alter table public.commission_requests enable row level security;
alter table public.inquiries enable row level security;
alter table public.chat_messages enable row level security;

drop policy if exists "public can create commission requests" on public.commission_requests;
create policy "public can create commission requests"
  on public.commission_requests
  for insert
  to anon
  with check (true);

drop policy if exists "public can create inquiries" on public.inquiries;
create policy "public can create inquiries"
  on public.inquiries
  for insert
  to anon
  with check (true);

drop policy if exists "public can create chat messages" on public.chat_messages;
create policy "public can create chat messages"
  on public.chat_messages
  for insert
  to anon
  with check (
    sender ~ '^[MP]-[A-Z0-9]{6}$'
    and char_length(message) between 1 and 2000
  );

create or replace function public.get_chat_replies(p_visitor_code text)
returns table (id bigint, created_at timestamptz, message text)
language sql
security definer
set search_path = public
as $$
  select cm.id, cm.created_at, cm.message
  from public.chat_messages cm
  where p_visitor_code ~ '^[MP]-[A-Z0-9]{6}$'
    and cm.sender = 'ADMIN:' || p_visitor_code
  order by cm.created_at asc;
$$;

revoke all on function public.get_chat_replies(text) from public;
grant execute on function public.get_chat_replies(text) to anon, authenticated;

create or replace function public.get_chat_thread_messages(p_visitor_code text)
returns table (id bigint, created_at timestamptz, sender text, message text)
language sql
security definer
set search_path = public
as $$
  select cm.id, cm.created_at, cm.sender, cm.message
  from public.chat_messages cm
  where p_visitor_code ~ '^[MP]-[A-Z0-9]{6}$'
    and (
      cm.sender = p_visitor_code
      or cm.sender = 'ADMIN:' || p_visitor_code
    )
  order by cm.created_at asc;
$$;

revoke all on function public.get_chat_thread_messages(text) from public;
grant execute on function public.get_chat_thread_messages(text) to anon, authenticated;

drop policy if exists "admins manage chat messages" on public.chat_messages;
create policy "admins manage chat messages"
  on public.chat_messages
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

drop policy if exists "admins manage inquiries" on public.inquiries;
create policy "admins manage inquiries"
  on public.inquiries
  for all
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create table if not exists public.site_settings (
  id integer primary key default 1 check (id = 1),
  slot_status text not null default '접수중',
  total_slots integer not null default 0 check (total_slots >= 0),
  used_slots integer not null default 0 check (used_slots >= 0),
  average_period text not null default '',
  updated_at timestamptz not null default now()
);

alter table public.site_settings
add column if not exists profile_image_url text not null default '';
alter table public.site_settings add column if not exists profile_image_scale integer not null default 100;
alter table public.site_settings add column if not exists profile_image_x integer not null default 50;
alter table public.site_settings add column if not exists profile_image_y integer not null default 50;
alter table public.site_settings add column if not exists status_lookup_enabled boolean not null default true;

insert into public.site_settings (id) values (1) on conflict (id) do nothing;

alter table public.site_settings alter column slot_status set default '접수중';
update public.site_settings
set slot_status = case slot_status
  when 'OPEN' then '접수중'
  when 'CLOSED' then '준비중'
  when 'REST' then '휴식중'
  when '쉬는 중' then '휴식중'
  else slot_status
end
where slot_status in ('OPEN', 'CLOSED', 'REST', '쉬는 중');

create or replace function public.commission_applications_open()
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select coalesce((select slot_status <> '휴식중' from public.site_settings where id = 1), false)
$$;
revoke all on function public.commission_applications_open() from public;
grant execute on function public.commission_applications_open() to anon, authenticated;

drop policy if exists "public can create commission requests" on public.commission_requests;
create policy "public can create commission requests"
  on public.commission_requests
  for insert
  to anon
  with check (public.commission_applications_open());

create table if not exists public.notices (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  content text not null default '',
  published boolean not null default true
);

create table if not exists public.gallery_items (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  title text not null,
  category text not null default 'sd',
  price text not null default '',
  description text not null default '',
  image_url text not null,
  published boolean not null default true
);

create table if not exists public.admin_logs (
  id bigint generated by default as identity primary key,
  created_at timestamptz not null default now(),
  actor text not null default '',
  action text not null,
  detail text not null default ''
);

do $$
begin
  if not exists (
    select 1 from pg_publication_tables
    where pubname = 'supabase_realtime' and schemaname = 'public' and tablename = 'notices'
  ) then
    alter publication supabase_realtime add table public.notices;
  end if;
end $$;

alter table public.site_settings enable row level security;
alter table public.notices enable row level security;
alter table public.gallery_items enable row level security;
alter table public.admin_logs enable row level security;

drop policy if exists "public can read site settings" on public.site_settings;
create policy "public can read site settings" on public.site_settings for select to anon using (id = 1);

drop policy if exists "public can read published notices" on public.notices;
create policy "public can read published notices" on public.notices for select to anon using (published = true);
drop policy if exists "public can read published gallery" on public.gallery_items;
create policy "public can read published gallery" on public.gallery_items for select to anon using (published = true);

drop policy if exists "admins manage requests" on public.commission_requests;
create policy "admins manage requests" on public.commission_requests for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage settings" on public.site_settings;
create policy "admins manage settings" on public.site_settings for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage notices" on public.notices;
create policy "admins manage notices" on public.notices for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage gallery" on public.gallery_items;
create policy "admins manage gallery" on public.gallery_items for all to authenticated using (public.is_admin()) with check (public.is_admin());
drop policy if exists "admins manage logs" on public.admin_logs;
create policy "admins manage logs" on public.admin_logs for all to authenticated using (public.is_admin()) with check (public.is_admin());

drop function if exists public.get_public_site_state();
create function public.get_public_site_state()
returns table (slot_status text, total_slots integer, used_slots integer, average_period text, profile_image_url text, profile_image_scale integer, profile_image_x integer, profile_image_y integer, status_lookup_enabled boolean)
language sql security definer set search_path = public stable
as $$ select slot_status, total_slots, least(used_slots, total_slots), average_period, profile_image_url, profile_image_scale, profile_image_x, profile_image_y, status_lookup_enabled from public.site_settings where id = 1 $$;
grant execute on function public.get_public_site_state() to anon, authenticated;

drop function if exists public.lookup_commission_status(bigint, text);
create function public.lookup_commission_status(p_request_id bigint, p_email text)
returns table (request_id bigint, request_type text, status text, created_at timestamptz)
language sql
security definer
set search_path = public
stable
as $$
  select id, commission_requests.request_type, commission_requests.status, commission_requests.created_at
  from public.commission_requests
  where id = p_request_id
    and lower(trim(email)) = lower(trim(p_email))
  limit 1
$$;
revoke all on function public.lookup_commission_status(bigint, text) from public;
grant execute on function public.lookup_commission_status(bigint, text) to anon, authenticated;

create or replace function public.increment_slot_on_request()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  update public.site_settings
  set used_slots = least(total_slots, used_slots + 1), updated_at = now()
  where id = 1;
  return new;
end;
$$;
drop trigger if exists commission_request_slot_increment on public.commission_requests;
create trigger commission_request_slot_increment after insert on public.commission_requests
for each row execute function public.increment_slot_on_request();

create or replace function public.decrement_slot_on_request_delete()
returns trigger language plpgsql security definer set search_path = public
as $$
begin
  update public.site_settings
  set used_slots = greatest(0, used_slots - 1), updated_at = now()
  where id = 1;
  return old;
end;
$$;
drop trigger if exists commission_request_slot_decrement on public.commission_requests;
create trigger commission_request_slot_decrement after delete on public.commission_requests
for each row execute function public.decrement_slot_on_request_delete();

insert into storage.buckets (id, name, public)
values ('gallery', 'gallery', true)
on conflict (id) do update set public = true;
drop policy if exists "public reads gallery files" on storage.objects;
create policy "public reads gallery files" on storage.objects for select to public using (bucket_id = 'gallery');
drop policy if exists "admins upload gallery files" on storage.objects;
create policy "admins upload gallery files" on storage.objects for insert to authenticated with check (bucket_id = 'gallery' and public.is_admin());
drop policy if exists "admins update gallery files" on storage.objects;
create policy "admins update gallery files" on storage.objects for update to authenticated using (bucket_id = 'gallery' and public.is_admin()) with check (bucket_id = 'gallery' and public.is_admin());
drop policy if exists "admins delete gallery files" on storage.objects;
create policy "admins delete gallery files" on storage.objects for delete to authenticated using (bucket_id = 'gallery' and public.is_admin());

insert into storage.buckets (id, name, public) values ('request-files', 'request-files', false)
on conflict (id) do update set public = false;
drop policy if exists "visitors upload request files" on storage.objects;
create policy "visitors upload request files" on storage.objects for insert to anon with check (bucket_id = 'request-files');
drop policy if exists "admins upload request files" on storage.objects;
create policy "admins upload request files" on storage.objects for insert to authenticated with check (bucket_id = 'request-files' and public.is_admin());
drop policy if exists "admins read request files" on storage.objects;
create policy "admins read request files" on storage.objects for select to authenticated using (bucket_id = 'request-files' and public.is_admin());
drop policy if exists "admins delete request files" on storage.objects;
create policy "admins delete request files" on storage.objects for delete to authenticated using (bucket_id = 'request-files' and public.is_admin());

drop policy if exists "public reads profile image" on storage.objects;
insert into storage.buckets (id, name, public) values ('profile', 'profile', true)
on conflict (id) do update set public = true;
create policy "public reads profile image" on storage.objects for select to public using (bucket_id = 'profile');
drop policy if exists "admins upload profile image" on storage.objects;
create policy "admins upload profile image" on storage.objects for insert to authenticated with check (bucket_id = 'profile' and public.is_admin());
drop policy if exists "admins update profile image" on storage.objects;
create policy "admins update profile image" on storage.objects for update to authenticated using (bucket_id = 'profile' and public.is_admin()) with check (bucket_id = 'profile' and public.is_admin());
drop policy if exists "admins delete profile image" on storage.objects;
create policy "admins delete profile image" on storage.objects for delete to authenticated using (bucket_id = 'profile' and public.is_admin());
